# Generated by Django 4.2 on 2023-04-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='csv',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
