# Generated by Django 4.2 on 2023-04-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(max_length=60000, null=True),
        ),
    ]
