# Generated by Django 4.2 on 2023-04-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_order_items_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='csv',
            new_name='cvv',
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(null=True),
        ),
    ]
