# Generated by Django 4.2 on 2023-04-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_csv_order_cvv_order_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
    ]
