# Generated by Django 4.2 on 2023-04-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('In Delivery', 'In Delivery')], max_length=50, null=True),
        ),
    ]
